### ISSUE TITLE
gRPC + UWP + CMake

### ISSUE THREAD

**Issue by Noemata** [coderox/BlankApp#2]
You appear to be the best available authority on this … I've been trying to sort out how to build gRPC using CMake and integrate it into a UWP solution, preferably as a C++/WinRT variant rather than C++/CX.

I was wondering if you could shed some light on this.  At build 2019 Microsoft proposed using gRPC as a replacement for legacy communications options.  I drank the Koolaid enthusiastically.  Unfortunately I haven't been able to get to a working release UWP build ever since.  Debug is mostly working, but I have no prospect of getting anything into the store without a release build :-(

The nuget packages make it real easy to get started, but without the nuts and bolts build pieces sorted out I have no way of fixing things myself.

**Comment by johanlindfors** [comment]
Hello again, I have no experience with gRPC but I did a small investigation. My usual path of examining support of open source packages is by using VCPKG (github.com/microsoft/vcpkg) which is a great package manager which also can be configured through CMAKE. However, trying to build gRPC fails due to the dependency ABSEIL not being supported to build for UWP. With that said, I can't recommend proceeding with gRPC. Maybe reaching out to Google and see if they have any plans for UWP support. I know that they've done some work on making sure Angle runs on UWP so this might be the next step...

**Comment by Noemata** [comment]
Yes, that's exactly what I do (use vcpkg).  Unfortunately, it's Microsoft that has promoted gRPC for UWP.  There is a Nuget package that partially works with UWP.  The release build is crashing.  For a time, the release build wasn't building due to a .Net Native compiler problem which took months to correct.  That was fixed, but as you know, things keep moving forward and the real issue now appears to be the fact that Microsoft is no longer investing resources in UWP.  One of the best indications of that being that vcpkg did at one time generate gRPC libs for UWP.  No more.  Thank you very much for looking into this.

**Comment by Noemata** [comment]
I managed to get the folks working on VCPKG to fix the gRPC build problems, which was fantastic.  The rest came down to the gRPC managed layer and the way the .Net Native compiler failed to replicated expected .Net compile behavior.

The code fixes on the gRPC side took less than a couple hours.  I do have to wonder why Microsoft would recommend the tech and then not support it … unfortunately the real answer is rather nefarious.  UWP is being re-tooled without proper notice being given to devs.  The .Net Native compiler is going away, to be replaced by the .Net Core AOT variant, and the UWP UI stack is being redone also.  Yet another re-write because of poor design choices?  And at the expense of the developer community and the impact such moves will have on them.  Not good.  Thanks for having a look.

**Comment by Noemata** [comment]
Please close this issue.

**Comment by johanlindfors** [comment]
Glad to hear it worked out well!
